locations:
  location_adjective_chance: 0.6
  location_noun_chance: 0.7
  synonym_chance: 0.5
log_level: 'INFO'
owners:
  use_ethnicity: on
  name_ethnicity_mismatch_chance: 0.2
  race_table: interesting # human_only # Workaround; should figure out how to ultimately handle this key
save_directory: data/settlements
show_configuration: off
town:
  default_services:
    - Inn
    - Tavern
  default_shops:
    - General Store
    - Smithy
  race_table: interesting
trading_post:
  shops: 1-8
  default_shops:
    - general store
  services: 1-6
  default_services:
    - inn
  place_of_worship_chance: 0.5
  race_table: interesting #human_only  # common_only, standard, interesting, wild
village:
  race_table: interesting
verbose: off